// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ctor_mdy
SEXP ctor_mdy();
RcppExport SEXP RToolsTest_ctor_mdy() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(ctor_mdy());
    return __result;
END_RCPP
}
// ctor_ymd
SEXP ctor_ymd();
RcppExport SEXP RToolsTest_ctor_ymd() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(ctor_ymd());
    return __result;
END_RCPP
}
// ctor_int
SEXP ctor_int(int d);
RcppExport SEXP RToolsTest_ctor_int(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(ctor_int(d));
    return __result;
END_RCPP
}
