# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctor_mdy <- function() {
    .Call('RToolsTest_ctor_mdy', PACKAGE = 'RToolsTest')
}

ctor_ymd <- function() {
    .Call('RToolsTest_ctor_ymd', PACKAGE = 'RToolsTest')
}

ctor_int <- function(d) {
    .Call('RToolsTest_ctor_int', PACKAGE = 'RToolsTest', d)
}

